### ISSUE TITLE
[Loc] pre-config and post config failed info not localized both in output and pop up dialog

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode-makefile-tools#611]
**Environment**:
[VSCode 1.90.1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcode.visualstudio.com%2F&data=05%7C02%7Cv-phta%40microsoft.com%7C8a22e1689c32475b2bb808dc951b3b30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638549191526247366%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=wHeEZXxd2PJhz6owZnY3pwAMx%2BbTO3CH%2F%2Bq%2BTP%2BFYYk%3D&reserved=0) + Makefile Tools v0.10.9(pre-release)

**More info:**
Repro Language: All 13 loc languages
Repro platform: Windows, Linux, Mac

**Repro steps:**
1. Open VScode and change the display language to CHS
2. Clone the makefile project (such as: https://github.com/remonbonbon/makefile-example) and open it in VSCode
3. Click F1 to open command palette and input “Makefile: Pre-configure” or “Makefile: Pre-configure”, check the output log and pop up info localization status

**Expected result:**
Pre-config and Post-config failed info localized both in output and pop up dialog

**Actual result:**
Pre-config and Post-config failed info not localized both in output and pop up dialog 

Pre-config:
![image](https://github.com/microsoft/vscode-makefile-tools/assets/37648162/06a58521-2fd4-4f3c-b118-3dfc5b061407)

Post-config:
![image](https://github.com/microsoft/vscode-makefile-tools/assets/37648162/d55237c9-6fe5-4ba8-bd67-2724c3e8c0ad)

**Comment by gcampbell-msft** [comment]
Fixed in #615

**Comment by PhoebeTf** [comment]
@gcampbell-msft Verified with Makefile Tools v0.10.12, Pre-config and Post-config failed info has been localized in the pop up dialog, while still not localized for output info. Could you help to confirm do I need reactive this issue? Or just track the issue [610](https://github.com/microsoft/vscode-makefile-tools/issues/610) and verify the output info status after that issue fixed?
![image](https://github.com/user-attachments/assets/4a7a0ac0-f546-4e7b-a8d8-794fbf3cbffd)

![image](https://github.com/user-attachments/assets/7f37c21a-d80a-4fff-9aa1-50d3b103495f)

**Comment by PhoebeTf** [comment]
Got it and will verify the output info status again after issue https://github.com/microsoft/vscode-makefile-tools/issues/610 fixed.

**Comment by PhoebeTf** [comment]
@gcampbell-msft Verified with Makefile Tools v0.10.21(pre-release), the output info for pre and post config has been localized, while the **output info** for post-config have been changed as _same with_ pop up dialog info, _is this expected_? Do I need create a new issue to track it?
CHS:
![image](https://github.com/user-attachments/assets/49aca3c9-9cde-47dc-9bf3-87e3f43e0e93)

ENU:
![image](https://github.com/user-attachments/assets/72986dea-406c-4408-8fd3-3c990e2ea438)

**Comment by gcampbell-msft** [comment]
@PhoebeTf Sorry, I'm not fully understanding. What is the issue? What happened before versus now?

**Comment by PhoebeTf** [comment]
@gcampbell-msft Sorry for confused you, the new issue is **output info for post-config have been changed** from "_No post-configure script is set in settings. Make sure a post-configuration script path is defined with makefile.postConfigureScript._" to "_Post-configure failed: no script provided._", which is same with pop up dialog info, is this expected?

**Detailed screenshot as below:**
MakefileTools V0.9.10: 
"_No post-configure script is set in settings. Make sure a post-configuration script path is defined with makefile.postConfigureScript._"
![image](https://github.com/user-attachments/assets/944b7c7b-3244-49b5-8023-887af45333bd)

MakefileTools V0.10.21(pre-release): 
"_Post-configure failed: no script provided._"
![image](https://github.com/user-attachments/assets/ed1b4914-8846-421c-9fdf-15150481891d)

**Comment by gcampbell-msft** [comment]
@PhoebeTf Thanks for checking, I have a PR for this here: #632

**Comment by Yingzi1234** [comment]
@gcampbell-msft @PhoebeTf This issue has been fixed on latest Makefile tools version v0.11.4(pre-release), you can get the details below. Thank you!
![image](https://github.com/user-attachments/assets/0562c837-6e8d-4d54-987e-82dffddacbbc)


> @gcampbell-msft Sorry for confused you, the new issue is **output info for post-config have been changed** from "_No post-configure script is set in settings. Make sure a post-configuration script path is defined with makefile.postConfigureScript._" to "_Post-configure failed: no script provided._", which is same with pop up dialog info, is this expected?
> 
> **Detailed screenshot as below:** MakefileTools V0.9.10: "_No post-configure script is set in settings. Make sure a post-configuration script path is defined with makefile.postConfigureScript._" ![image](https://private-user-images.githubusercontent.com/37648162/354954878-944b7c7b-3244-49b5-8023-887af45333bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTcyMDYsIm5iZiI6MTcyNDA1NjkwNiwicGF0aCI6Ii8zNzY0ODE2Mi8zNTQ5NTQ4NzgtOTQ0YjdjN2ItMzI0NC00OWI1LTgwMjMtODg3YWY0NTMzM2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA4NDE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMmJkMzNkZjc1MTc3NmI3ZTUyYjY0MzM1NTdmNTVjOGYzNzAxNzAwYjVmNzYyZTc3ZWY5MTFjMjgyZmVkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.53RkRuptcbNyq5Tv-kq6CLr7D6tb2FocmhGFyPrth0A)
> 
> MakefileTools V0.10.21(pre-release): "_Post-configure failed: no script provided._" ![image](https://private-user-images.githubusercontent.com/37648162/354954942-ed1b4914-8846-421c-9fdf-15150481891d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTcyMDYsIm5iZiI6MTcyNDA1NjkwNiwicGF0aCI6Ii8zNzY0ODE2Mi8zNTQ5NTQ5NDItZWQxYjQ5MTQtODg0Ni00MjFjLTlmZGYtMTUxNTA0ODE4OTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA4NDE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlOTU3OTlkN2VjOTk1OGNlOTAxYjZlNDEyZGUxNDE0OWNmYzQ4M2RiZmZlYWQzNzdlYWQxMTcxMTg2MmM4NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bhn2Gr1ZNcoLcAoJ8p9aRsiNJmAYcAzdpM5vNmqiDxc)
