### ISSUE TITLE
"$" appears in the pre-configured and post-configured Makefile tools popup dialogues

### ISSUE THREAD

**Issue by Yingzi1234** [microsoft/vscode-makefile-tools#635]
**More info:**
1. This issue is reproduced on v0.9.10(release), so it is not a regression issue
2. Repro platform: Windows, Linux, Mac
 
**Repro steps:**
1. Open VSCode and clone the repository [https://github.com/remonbonbon/makefile-example.git](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fremonbonbon%2Fmakefile-example.git&data=05%7C02%7Cv-cathyzhang%40microsoft.com%7C9325a79d39494e46441f08dcb62d301f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638585552453958209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ccPMGzjR5fYyfMlPFNIQGxbIbShTiihKrp5ltx%2Bkeo0%3D&reserved=0)
2. Create a pre-configure file or post-configure, such as: “preConfigureScript.bat”
3. Copy the contents: ECHO “PRECONFIGURE” %~1 to this file
4. Copy the path to the "Makefile: Pre Configrue Script” settings
5. Click F1 to run command "Makefile: Pre-configure" 
6. Check the string in popup dialog

**Expected result:**
No "$" appears in the pre-configured and post-configured Makefile tools popup dialogues
 
**Actual result:**
"$" appears in the pre-configure and post-configure Makefile tools popup dialogues

**pre-configure:** 
![image](https://github.com/user-attachments/assets/b747d1b4-4533-48f5-962d-f5e4d4c8f66a)

**post-configure:**
![image](https://github.com/user-attachments/assets/fbd0910a-401b-4f02-8de1-f70fcacd3d56)

**Comment by gcampbell-msft** [comment]
Fixed by #634

**Comment by Yingzi1234** [comment]
@gcampbell-msft I apologize that this issue has not been fully resolved, so I've turned it open on. The “$” will still appear in the configured Makefile tool popup dialog box. You can get the details below. Thank you!

ENV:
Makefile tools verison: v0.11.6(pre-release)
vscode verison: 1.92.2

Post-configure:
![image](https://github.com/user-attachments/assets/6482484f-efbf-4a21-9626-230e871a7435)

pre-configure:
![image](https://github.com/user-attachments/assets/5f90069b-4ab7-4bd7-9283-056804f4ca70)

**Comment by Yingzi1234** [comment]
@gcampbell-msft I'm sorry to say that this issue still hasn't been resolved by this PR https://github.com/microsoft/vscode-makefile-tools/pull/643 , so I've turned it back on. “Post-configuration success” has not been translated yet. You can get the details below. Thanks!
![image](https://github.com/user-attachments/assets/69e9465b-ce9e-4be9-95d2-70b11bd4fdf3)

**Comment by gcampbell-msft** [comment]
Looks like this is fixed in most recent prelease, closing.

**Comment by Yingzi1234** [comment]
@gcampbell-msft Thank you very much for reconfirming, this issue has been fixed on latest Makefile Tools version: 0.12.4(pre-release), you can get the details below. Thank you!
![Image](https://github.com/user-attachments/assets/52ca43f3-37a9-4a33-b59b-ee2406bbd504)
